Repository metal3-io/hardware-classification-controller, pull requests merged in 2020-09, with the labels that each got.

#38 Updated dev-setup.md
  docs/dev-setup.md
Labels: approved, lgtm, ok-to-test, size/M

#39 Added user guide document.
  docs/user-guide.md
Labels: approved, lgtm, ok-to-test, size/L

#43 Added unit test cases for utils.go
  controllers/hardwareclassification_controller.go
  hcmanager/hcmanager_suite_test.go
  hcmanager/hcmanager_test_data.go
  hcmanager/labels.go
  hcmanager/utils.go
  hcmanager/utils_test.go
Labels: approved, lgtm, ok-to-test, size/L

#45 Classification And Validation Framework Test Cases
  hcmanager/classification_filter_test.go
  hcmanager/hcmanager_data_test.go
Labels: approved, lgtm, ok-to-test, size/L

#46 Updated links in dev-setup.md and user-guide.md.
  docs/dev-setup.md
  docs/user-guide.md
Labels: approved, lgtm, ok-to-test, size/XS

#44 Updated readme.md
  README.md
  docs/configuration.md
Labels: approved, lgtm, ok-to-test, size/M

#47 Added unit test cases for labels.go
  hcmanager/hcmanager_data_test.go
  hcmanager/labels_test.go
Labels: approved, lgtm, ok-to-test, size/L
