Repository metal3-io/hardware-classification-controller, pull requests merged in 2020-07, with the labels that each got.

#28 leader election id must be configured.
  main.go
Labels: approved, lgtm, ok-to-test, size/XS

#27 Changed namespace to hardware-classification
  Makefile
  config/default/kustomization.yaml
  config/kustomization.yaml
  config/manager/manager.yaml
  config/namespace.yaml
  config/rbac/role.yaml
  controllers/hardwareclassification_controller.go
  main.go
Labels: approved, lgtm, ok-to-test, size/S

#26 Implemented host classification framework
  api/v1alpha1/hardwareclassification_types.go
  config/manager/kustomization.yaml
  controllers/hardwareclassification_controller.go
  hcmanager/classification_filter.go
  hcmanager/manager.go
  hcmanager/utils.go
  hcmanager/validation.go
Labels: approved, lgtm, ok-to-test, size/L

#29 Implementation of label selector
  api/v1alpha1/hardwareclassification_types.go
  controllers/hardwareclassification_controller.go
  hcmanager/labels.go
  hcmanager/manager.go
Labels: approved, lgtm, ok-to-test, size/L
