Repository metal3-io/hardware-classification-controller, pull requests merged in 2020-08, with the labels that each got.

#30 Changed module path of hwcc
  PROJECT
  controllers/hardwareclassification_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  hcmanager/classification_filter.go
  hcmanager/labels.go
  hcmanager/manager.go
  hcmanager/utils.go
  hcmanager/validation.go
  main.go
Labels: approved, lgtm, ok-to-test, size/XL

#34 Fixed Bugs #31 #32 #33
  controllers/hardwareclassification_controller.go
  hcmanager/classification_filter.go
  hcmanager/labels.go
Labels: approved, lgtm, ok-to-test, size/M

#37 Label was getting deleted if state of node is changed (Ready -> Provision)
  hcmanager/labels.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#35 Updated api guide
  docs/api.md
Labels: approved, lgtm, ok-to-test, size/L
