Repository metal3-io/hardware-classification-controller, pull requests merged in 2021-06, with the labels that each got.

#69 Adding Rule book for Disk and NIC selection.
  docs/rule_book.md
Labels: approved, lgtm, ok-to-test, size/M

#63 NIC's sub parameter NICSelector implementation and unit test cases.
  api/v1alpha1/hardwareclassification_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  classifier/nic.go
  classifier/nic_test.go
  config/crd/bases/metal3.io_hardwareclassifications.yaml
  config/samples/metal3.io_v1alpha1_hardwareclassification.yaml
Labels: approved, lgtm, ok-to-test, size/L

#77 Corrected maxCount value for disk
  classifier/disk.go
Labels: approved, lgtm, ok-to-test, size/XS
